%YAML:1.0


#--------------------------------------------------------------------------------------------
# Stereo Rectification. Only if you need to pre-rectify the images.
# Camera.fx, .fy, etc must be the same as in LEFT.P
#--------------------------------------------------------------------------------------------
LEFT.height: 240
LEFT.width: 320
LEFT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [-0.0047, 0.1735, 0.0058, 0.0051, -0.3301]
LEFT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [177.0648, 0.2860, 171.6758, 0.0, 235.9113, 129.4879, 0.0, 0.0, 1.0]


RIGHT.height: 240
RIGHT.width: 320
RIGHT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [-0.0044, 0.1075, 0.0047, 0.0014, -0.1063]
RIGHT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [176.6538, 0.0684, 159.2211, 0.0, 235.3501, 108.2461, 0.0, 0.0, 1]


LEFT2RIGHT.R: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.9988, 0.00083888, -0.0489, -0.0021, 0.9997, -0.0257, 0.0488, 0.0258, 0.9985]
   
LEFT2RIGHT.T: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [-97.8850, 3.4232, -0.9254]

